export const PK_COLUMNS = ['USER_ID', 'YEAR', 'EVALUATION'];

export const COLUMNS_TO_DISPLAY = [
  'FULL_NAME', 'JOB_TITLE_CZ', 'USERNAME',
  'L2_ORGANIZATION_UNIT_NAME_CZ', 'L3_ORGANIZATION_UNIT_NAME_CZ',
  'L4_ORGANIZATION_UNIT_NAME_CZ', 'L2_HEAD_OF_UNIT_FULL_NAME',
  'L3_HEAD_OF_UNIT_FULL_NAME', 'L4_HEAD_OF_UNIT_FULL_NAME',
  'MES_DPP_STATUS', 'DIRECT_MANAGER_FULL_NAME', 'LAST_EVALUATION',
  'VYKON_PREVIOUS', 'HODNOTY_PREVIOUS', 'POTENCIAL_PREVIOUS',
  'VYKON_SYSTEM', 'HODNOTY_SYSTEM', 'IS_LOCKED',
];

export const EDITABLE_COLUMNS = [
  'VYKON', 'HODNOTY', 'POTENCIAL', 'MOZNY_KARIERNI_POSUN',
  'PRAVDEPODOBNOST_ODCHODU', 'NASTUPCE', 'POZNAMKY',
];

export const FILTER_MANAGEMENT_COLUMNS = [
  'FULL_NAME', 'JOB_TITLE_CZ', 'L2_ORGANIZATION_UNIT_NAME_CZ',
  'L3_ORGANIZATION_UNIT_NAME_CZ', 'L4_ORGANIZATION_UNIT_NAME_CZ',
  'L2_HEAD_OF_UNIT_FULL_NAME', 'L3_HEAD_OF_UNIT_FULL_NAME',
  'L4_HEAD_OF_UNIT_FULL_NAME', 'DIRECT_MANAGER_FULL_NAME', 'USERNAME',
];

export const FILTER_COLUMNS = [
  'L2_ORGANIZATION_UNIT_NAME_CZ', 'L3_ORGANIZATION_UNIT_NAME_CZ',
  'L4_ORGANIZATION_UNIT_NAME_CZ', 'L2_HEAD_OF_UNIT_FULL_NAME',
  'L3_HEAD_OF_UNIT_FULL_NAME', 'L4_HEAD_OF_UNIT_FULL_NAME',
  'JOB_TITLE_CZ', 'DIRECT_MANAGER_FULL_NAME',
];

export const ROLES = {
  BP: 'BP',
  LC: 'LC',
  MA: 'MA',
  DEV: 'DEV',
  TEST: 'TEST',
};
